export const kabupaten = [
  { name: 'Luwu Utara', coords: { top: '10%', left: '65%' }, link: 'luwu_utara' },
  { name: 'Luwu Timur', coords: { top: '8%', left: '30%' }, link: 'luwu_timur' },
  { name: 'Toraja Utara', coords: { top: '17%', left: '18%' }, link: 'toraja_utara' },
  { name: 'Tana Toraja', coords: { top: '23%', left: '15%' }, link: 'tana_toraja' },
  { name: 'Palopo', coords: { top: '20%', left: '33%' }, link: 'palopo' },
  { name: 'Luwu', coords: { top: '28%', left: '36%' }, link: 'luwu' },
  { name: 'Enrekang', coords: { top: '30%', left: '22%' }, link: 'enrekang' },
  { name: 'Pinrang', coords: { top: '33%', left: '12%' }, link: 'pinrang' },
  { name: 'Sidrap', coords: { top: '35%', left: '31%' }, link: 'sidrap' },
  { name: 'Wajo', coords: { top: '43%', left: '35%' }, link: 'wajo' },
  { name: 'Pare-pare', coords: { top: '43%', left: '13%' }, link: 'parepare' },
  { name: 'Bone', coords: { top: '56%', left: '35%' }, link: 'bone' },
  { name: 'Soppeng', coords: { top: '48%', left: '23%' }, link: 'soppeng' },
  { name: 'Barru', coords: { top: '52%', left: '17%' }, link: 'barru' },
  { name: 'Pangkep', coords: { top: '59%', left: '13%' }, link: 'pangkep' },
  { name: 'Maros', coords: { top: '64%', left: '17%' }, link: 'maros' },
  { name: 'Makassar', coords: { top: '66%', left: '7%' }, link: 'makassar' },
  { name: 'Gowa', coords: { top: '70%', left: '20%' }, link: 'gowa' },
  { name: 'Sinjai', coords: { top: '67%', left: '35%' }, link: 'sinjai' },
  { name: 'Bulukumba', coords: { top: '72%', left: '35%' }, link: 'bulukumba' },
  { name: 'Bantaeng', coords: { top: '74%', left: '25%' }, link: 'bantaeng' },
  { name: 'Jeneponto', coords: { top: '75%', left: '13%' }, link: 'jeneponto' },
  { name: 'Takalar', coords: { top: '71%', left: '10%' }, link: 'takalar' },
  { name: 'Selayar', coords: { top: '85%', left: '47%' }, link: 'selayar' }
]
